// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DbmindCareContext))]
    [Migration("20251225203140_FixFacturaDetalleRelations")]
    partial class FixFacturaDetalleRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.DatosPersonale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("ImagePerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipiosId")
                        .HasColumnType("int")
                        .HasColumnName("municipios_id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("telefono")
                        .IsFixedLength();

                    b.Property<string>("TipoId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("tipo_id");

                    b.HasKey("Id")
                        .HasName("PK__datos_pe__3213E83F9EE094A3");

                    b.ToTable("datos_personales", (string)null);
                });

            modelBuilder.Entity("API.Models.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Validado")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("validado");

                    b.HasKey("Id")
                        .HasName("PK__especial__3213E83F6D6BED28");

                    b.ToTable("especialidad", (string)null);
                });

            modelBuilder.Entity("API.Models.Idioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__idiomas__3213E83F25844C9A");

                    b.ToTable("idioma", (string)null);
                });

            modelBuilder.Entity("API.Models.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("departamento_id");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__municipi__01C9EB99A83DE567");

                    b.ToTable("municipio", (string)null);
                });

            modelBuilder.Entity("API.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Estado")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDatosPersonales")
                        .HasColumnType("int")
                        .HasColumnName("id_datos_personales");

                    b.HasKey("Id")
                        .HasName("PK__paciente__3213E83FA85C8254");

                    b.HasIndex("IdDatosPersonales")
                        .IsUnique()
                        .HasFilter("[id_datos_personales] IS NOT NULL");

                    b.ToTable("paciente", (string)null);
                });

            modelBuilder.Entity("API.Models.Psicologo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<int?>("Experiencia")
                        .HasColumnType("int")
                        .HasColumnName("experiencia");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("File_cv")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("file_cv");

                    b.Property<int>("IdDatosPersonales")
                        .HasColumnType("int")
                        .HasColumnName("id_datos_personales");

                    b.Property<string>("ImagePerfil")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ImagePerfil");

                    b.Property<string>("Validado")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("validado");

                    b.Property<string>("sugerencias")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("sugerencias");

                    b.HasKey("Id")
                        .HasName("PK__psicolog__3213E83FD1565457");

                    b.HasIndex("IdDatosPersonales");

                    b.ToTable("psicologo", (string)null);
                });

            modelBuilder.Entity("API.Models.PsicologoEspecialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdEspecialidad")
                        .HasColumnType("int")
                        .HasColumnName("id_especialidad");

                    b.Property<int?>("IdPsicologo")
                        .HasColumnType("int")
                        .HasColumnName("id_psicologo");

                    b.Property<string>("Validado")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("validado");

                    b.HasKey("Id")
                        .HasName("PK__psicolog__3213E83F1D5424A2");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdPsicologo");

                    b.ToTable("psicologo_especialidad", (string)null);
                });

            modelBuilder.Entity("API.Models.PsicologoIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdIdioma")
                        .HasColumnType("int")
                        .HasColumnName("id_idioma");

                    b.Property<int?>("IdPsicologo")
                        .HasColumnType("int")
                        .HasColumnName("id_psicologo");

                    b.HasKey("Id")
                        .HasName("PK__psicolog__3214EC07431E6529");

                    b.HasIndex("IdIdioma");

                    b.HasIndex("IdPsicologo");

                    b.ToTable("psicologo_idioma", (string)null);
                });

            modelBuilder.Entity("API.Models.PsicologoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPsicologo")
                        .HasColumnType("int")
                        .HasColumnName("id_psicologo");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PK__psicolog__3214EC07EB7DAE71");

                    b.HasIndex("IdPsicologo");

                    b.HasIndex("IdServicio");

                    b.ToTable("psicologo_servicios", (string)null);
                });

            modelBuilder.Entity("API.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__servicio__3214EC07DF33398E");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("Data.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdDatosPersonales")
                        .HasColumnType("int")
                        .HasColumnName("id_datos_personales");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<int>("idPerfil")
                        .HasColumnType("int")
                        .HasColumnName("id_perfil");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83FFA64AA69");

                    b.HasIndex("IdDatosPersonales")
                        .IsUnique();

                    b.HasIndex("idPerfil")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int")
                        .HasColumnName("DiaSemana");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("Idpsicologo")
                        .HasColumnType("int")
                        .HasColumnName("Idpsicologo");

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<int>("mes")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Agenda__3214EC07EFBA9345");

                    b.HasIndex("Idpsicologo")
                        .IsUnique();

                    b.ToTable("Agenda", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("Idpaciente")
                        .HasColumnType("int")
                        .HasColumnName("Idpaciente");

                    b.Property<int>("Idpsicologo")
                        .HasColumnType("int")
                        .HasColumnName("Idpsicologo");

                    b.Property<int>("Idservicio")
                        .HasColumnType("int")
                        .HasColumnName("Idservicio");

                    b.Property<int>("Idterapia")
                        .HasColumnType("int")
                        .HasColumnName("Idterapia");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("pagado")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__cita__3214EC07E7201A27");

                    b.HasIndex("Idpsicologo")
                        .IsUnique();

                    b.HasIndex("Idservicio")
                        .IsUnique();

                    b.ToTable("Cita", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ConceptoPsicologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Compromisos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("COMPROMISOS");

                    b.Property<string>("DiagnosticoPrincipal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DIAGNOSTICO_PRINCIPAL");

                    b.Property<string>("DiagnosticoRelacionado1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DIAGNOSTICO_RELACIONADO_1");

                    b.Property<string>("DiagnosticoRelacionado2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DIAGNOSTICO_RELACIONADO_2");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdHistoriaClinica")
                        .HasColumnType("int")
                        .HasColumnName("id_historia_clinica");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<string>("Objetivos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("OBJETIVOS");

                    b.Property<string>("PlanDeTratamiento")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PLAN_DE_TRATAMIENTO");

                    b.Property<string>("Recomendaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("RECOMENDACIONES");

                    b.HasKey("Id");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.HasIndex("IdUsuarioCreacion");

                    b.ToTable("CONCEPTO_PSICOLOGICO", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK_departamento");

                    b.ToTable("departamento", (string)null);
                });

            modelBuilder.Entity("Domain.Models.DesarrolloPsicosexual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EdadDeDesarrollo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EDAD_DE_DESARROLLO");

                    b.Property<string>("EdadDeInicioDeRelacionesSexuales")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EDAD_DE_INICIO_DE_RELACIONES_SEXUALES");

                    b.Property<string>("EnfermedadesDeTransmisionSexual")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ENFERMEDADES_DE_TRANSMISION_SEXUAL");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("HaSidoVictimaDeAbusoSexual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HA_SIDO_VICTIMA_DE_ABUSO_SEXUAL");

                    b.Property<int>("IdHistoriaClinica")
                        .HasColumnType("int")
                        .HasColumnName("id_historia_clinica");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<string>("IdentidadSexual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IDENTIDAD_SEXUAL");

                    b.Property<string>("MadreOPadreAdolescente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MADRE_O_PADRE_ADOLESCENTE");

                    b.Property<string>("OrientacionSexual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ORIENTACION_SEXUAL");

                    b.Property<string>("UsoDeMetodosDePlanificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USO_DE_METODOS_DE_PLANIFICACION");

                    b.HasKey("Id");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.HasIndex("IdUsuarioCreacion");

                    b.ToTable("DESARROLLO_PSICOSEXUAL", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ExamenEstadoMental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Afecto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AFECTO");

                    b.Property<string>("Atencion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ATENCION");

                    b.Property<string>("ConductaMotora")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CONDUCTA_MOTORA");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdHistoriaClinica")
                        .HasColumnType("int")
                        .HasColumnName("id_historia_clinica");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<string>("Inteligencia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("INTELIGENCIA");

                    b.Property<string>("Lenguaje")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LENGUAJE");

                    b.Property<string>("Memoria")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MEMORIA");

                    b.Property<string>("NivelDeConciencia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NIVEL_DE_CONCIENCIA");

                    b.Property<string>("NivelDeRazonamiento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NIVEL_DE_RAZONAMIENTO");

                    b.Property<string>("Orientacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ORIENTACION");

                    b.Property<string>("PatronDeAlimentacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PATRON_DE_ALIMENTACION");

                    b.Property<string>("Pensamiento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PENSAMIENTO");

                    b.Property<string>("PorteYActitud")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PORTE_Y_ACTITUD");

                    b.Property<string>("Sensopercepcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SENSOPERCEPCION");

                    b.Property<string>("Sueno")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SUENO");

                    b.HasKey("Id");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.HasIndex("IdUsuarioCreacion");

                    b.ToTable("EXAMEN_DE_ESTADO_MENTAL", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cufe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JsonDian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idPaciente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idPaciente");

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("Domain.Models.FacturaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int>("IdTerapia")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ispackage")
                        .HasColumnType("bit")
                        .HasColumnName("ispackage");

                    b.HasKey("Id");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdTerapia");

                    b.ToTable("FacturaDetalles");
                });

            modelBuilder.Entity("Domain.Models.HistoriaAcademica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdaptacionInicial")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ADAPTACION_INICIAL");

                    b.Property<string>("AnosPerdidos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ANOS_PERDIDOS");

                    b.Property<string>("CursoActual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CURSO_ACTUAL");

                    b.Property<string>("DesempenoAcademico")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DESEMPENO_ACADEMICO");

                    b.Property<string>("EdadDeIngresoALaEscuela")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EDAD_DE_INGRESO_A_LA_ESCUELA");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdHistoriaClinica")
                        .HasColumnType("int")
                        .HasColumnName("id_historia_clinica");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<string>("MateriaQueSeFacilitaYLaQueSeDificulta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MATERIA_QUE_SE_FACILITA_Y_LA_QUE_SE_DIFICULTA");

                    b.Property<string>("TiempoDiarioDeEstudioHoras")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TIEMPO_DIARIO_DE_ESTUDIO_HORAS");

                    b.HasKey("Id");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.HasIndex("IdUsuarioCreacion");

                    b.ToTable("HISTORIA_ACADEMICA", (string)null);
                });

            modelBuilder.Entity("Domain.Models.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<int?>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("IdPaciente");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.HasKey("Id");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.HasIndex("IdUsuarioCreacion");

                    b.ToTable("HISTORIA_CLINICA", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Hobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdDatosPersonales")
                        .HasColumnType("int")
                        .HasColumnName("iddatospersonales");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__hobbies__3213E83FAE9B75BC");

                    b.HasIndex("IdDatosPersonales");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Hobbies", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MentalPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AntecedentesDeAutolesion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ANTECEDENTES_DE_AUTOLESION");

                    b.Property<string>("ConsumoDeAlcohol")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CONSUMO_DE_ALCOHOL");

                    b.Property<string>("ConsumoDeSustanciasPsicoactivas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CONSUMO_DE_SUSTANCIAS_PSICOACTIVAS");

                    b.Property<string>("DiscapacidadCognitiva")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DISCAPACIDAD_COGNITIVA");

                    b.Property<string>("DxDeSaludMental")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DX_DE_SALUD_MENTAL");

                    b.Property<string>("EnfermedadesFamiliaresHeredables")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ENFERMEDADES_FAMILIARES_HEREDABLES");

                    b.Property<string>("Epilepsia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EPILEPSIA");

                    b.Property<string>("EventosTraumaticos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("EVENTOS_TRAUMATICOS");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdHistoriaClinica")
                        .HasColumnType("int")
                        .HasColumnName("id_historia_clinica");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<string>("IntentoDeSuicidio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("INTENTO_DE_SUICIDIO");

                    b.Property<string>("InternacionesEnCentrosPsiquiatricos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("INTERNACIONES_EN_CENTROS_PSIQUIATRICOS");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("OBSERVACIONES");

                    b.Property<string>("SeEncuentraMedicado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SE_ENCUENTRA_MEDICADO");

                    b.HasKey("Id");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.HasIndex("IdUsuarioCreacion");

                    b.ToTable("MENTAL_PERSONAL", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Pagos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NumeroSesion")
                        .HasColumnType("int");

                    b.Property<int?>("PaqueteId")
                        .HasColumnType("int");

                    b.Property<int>("PsicologoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Domain.Models.PayUConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("merchantid");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paymentmethodtype");

                    b.Property<string>("RawBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rawBody");

                    b.Property<string>("ReferenceSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referencesale");

                    b.Property<string>("ResponseCodePol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("responsecodepol");

                    b.Property<string>("StatePol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("statepol");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PayUConfirmations", (string)null);
                });

            modelBuilder.Entity("Domain.Models.RazonesSintomasConducta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdHistoriaClinica")
                        .HasColumnType("int")
                        .HasColumnName("id_historia_clinica");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<string>("RelacionadosAmbienteSocial")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RELACIONADOS_AMBIENTE_SOCIAL");

                    b.Property<string>("RelacionadosAmbientesAcademicos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RELACIONADOS_AMBIENTES_ACADEMICOS");

                    b.Property<string>("RelacionadosAmbientesFamiliares")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RELACIONADOS_AMBIENTES_FAMILIARES");

                    b.Property<string>("RelacionadosCaracteristicasDelIndividuo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RELACIONADOS_CARACTERISTICAS_DEL_INDIVIDUO");

                    b.HasKey("Id");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.HasIndex("IdUsuarioCreacion");

                    b.ToTable("RAZONES_DE_SINTOMAS_CONDUCTA", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCita")
                        .HasColumnType("int")
                        .HasColumnName("IdCita");

                    b.Property<string>("TokenHost")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("tokenHost");

                    b.Property<string>("TokenHuesped")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("tokenHuesped");

                    b.Property<string>("UrlHost")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("urlhost");

                    b.Property<string>("UrlHuesped")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("urlhuesped");

                    b.Property<DateTime>("fechahora")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__sala__3214EC0779310298");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.ToTable("Sala", (string)null);
                });

            modelBuilder.Entity("Domain.Models.SignosFisicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cicatrices")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CICATRICES");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Fracturas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FRACTURAS");

                    b.Property<string>("Hematoma")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HEMATOMA");

                    b.Property<int>("IdHistoriaClinica")
                        .HasColumnType("int")
                        .HasColumnName("id_historia_clinica");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<string>("Laceraciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LACERACIONES");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("OBSERVACIONES");

                    b.Property<string>("Quemaduras")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("QUEMADURAS");

                    b.HasKey("Id");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.HasIndex("IdUsuarioCreacion");

                    b.ToTable("SIGNOS_FISICOS", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Terapia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioActualizacion");

                    b.Property<int>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuarioCreacion");

                    b.Property<int>("Idpsicologo")
                        .HasColumnType("int");

                    b.Property<int>("Idservicio")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSesiones")
                        .HasColumnType("int")
                        .HasColumnName("NumeroSesiones");

                    b.Property<bool>("espaquete")
                        .HasColumnType("bit");

                    b.Property<int>("idPaciente")
                        .HasColumnType("int");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Idpsicologo");

                    b.HasIndex("Idservicio");

                    b.HasIndex("idPaciente");

                    b.ToTable("Terapia", (string)null);
                });

            modelBuilder.Entity("Domain.Models.carrito_de_compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Es_Paquete");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaActualizacion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdPsicologo")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSesiones")
                        .HasColumnType("int")
                        .HasColumnName("Numero_Sesiones");

                    b.Property<decimal>("ValorServicio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorServicio");

                    b.HasKey("Id");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdPsicologo");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdUsuarioActualizacion");

                    b.ToTable("carrito_de_compra", (string)null);
                });

            modelBuilder.Entity("API.Models.Paciente", b =>
                {
                    b.HasOne("API.Models.DatosPersonale", "DatosPersonale")
                        .WithOne("Paciente")
                        .HasForeignKey("API.Models.Paciente", "IdDatosPersonales")
                        .HasConstraintName("FK_paciente_datos_personales");

                    b.Navigation("DatosPersonale");
                });

            modelBuilder.Entity("API.Models.Psicologo", b =>
                {
                    b.HasOne("API.Models.DatosPersonale", "IdDatosPersonalesNavigation")
                        .WithMany("Psicologos")
                        .HasForeignKey("IdDatosPersonales")
                        .IsRequired()
                        .HasConstraintName("FK_psicologo_datos_personales");

                    b.Navigation("IdDatosPersonalesNavigation");
                });

            modelBuilder.Entity("API.Models.PsicologoEspecialidad", b =>
                {
                    b.HasOne("API.Models.Especialidad", "IdEspecialidadNavigation")
                        .WithMany("PsicologoEspecialidads")
                        .HasForeignKey("IdEspecialidad")
                        .HasConstraintName("FK_psicologo_especialidad_especialidad");

                    b.HasOne("API.Models.Psicologo", "IdPsicologoNavigation")
                        .WithMany("PsicologoEspecialidads")
                        .HasForeignKey("IdPsicologo")
                        .HasConstraintName("FK_psicologo_especialidad_psicologo");

                    b.Navigation("IdEspecialidadNavigation");

                    b.Navigation("IdPsicologoNavigation");
                });

            modelBuilder.Entity("API.Models.PsicologoIdioma", b =>
                {
                    b.HasOne("API.Models.Idioma", "IdIdiomaNavigation")
                        .WithMany("PsicologoIdiomas")
                        .HasForeignKey("IdIdioma")
                        .IsRequired()
                        .HasConstraintName("FK_psicologo_idioma_idioma");

                    b.HasOne("API.Models.Psicologo", "IdPsicologoNavigation")
                        .WithMany("PsicologoIdiomas")
                        .HasForeignKey("IdPsicologo")
                        .HasConstraintName("FK_psicologo_idioma_psicologo");

                    b.Navigation("IdIdiomaNavigation");

                    b.Navigation("IdPsicologoNavigation");
                });

            modelBuilder.Entity("API.Models.PsicologoServicio", b =>
                {
                    b.HasOne("API.Models.Psicologo", "IdPsicologoNavigation")
                        .WithMany("PsicologoServicios")
                        .HasForeignKey("IdPsicologo")
                        .IsRequired()
                        .HasConstraintName("FK_psicologo_servicios_psicologo");

                    b.HasOne("API.Models.Servicio", "IdServicioNavigation")
                        .WithMany("PsicologoServicios")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK_psicologo_servicios_servicio");

                    b.Navigation("IdPsicologoNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.HasOne("API.Models.DatosPersonale", "IdDatosPersonalesNavigation")
                        .WithOne("User")
                        .HasForeignKey("Data.Models.User", "IdDatosPersonales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_persona");

                    b.HasOne("Data.Models.Perfil", "Perfil")
                        .WithOne("User")
                        .HasForeignKey("Data.Models.User", "idPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDatosPersonalesNavigation");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Domain.Models.Agenda", b =>
                {
                    b.HasOne("API.Models.Psicologo", "IdPsicologoNavigation")
                        .WithOne("Agenda")
                        .HasForeignKey("Domain.Models.Agenda", "Idpsicologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_agenda_psicologo");

                    b.Navigation("IdPsicologoNavigation");
                });

            modelBuilder.Entity("Domain.Models.Cita", b =>
                {
                    b.HasOne("API.Models.Psicologo", "psicologo")
                        .WithOne("cita")
                        .HasForeignKey("Domain.Models.Cita", "Idpsicologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Servicio", "servicio")
                        .WithOne("cita")
                        .HasForeignKey("Domain.Models.Cita", "Idservicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("psicologo");

                    b.Navigation("servicio");
                });

            modelBuilder.Entity("Domain.Models.ConceptoPsicologico", b =>
                {
                    b.HasOne("Domain.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("ConceptoPsicologico")
                        .HasForeignKey("IdHistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CONCEPTO_PSICOLOGICO_usario_actualizacion");

                    b.HasOne("Data.Models.User", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CONCEPTO_PSICOLOGICO_usario_creacion");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Models.DesarrolloPsicosexual", b =>
                {
                    b.HasOne("Domain.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("DesarrolloPsicosexual")
                        .HasForeignKey("IdHistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DESARROLLO_PSICOSEXUAL_usario_actualizacion");

                    b.HasOne("Data.Models.User", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DESARROLLO_PSICOSEXUAL_usario_creacion");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Models.ExamenEstadoMental", b =>
                {
                    b.HasOne("Domain.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("ExamenEstadoMental")
                        .HasForeignKey("IdHistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EXAMEN_DE_ESTADO_MENTAL_usario_actualizacion");

                    b.HasOne("Data.Models.User", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EXAMEN_DE_ESTADO_MENTAL_usario_creacion");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Models.Factura", b =>
                {
                    b.HasOne("API.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.Models.FacturaDetalle", b =>
                {
                    b.HasOne("Domain.Models.Factura", "Factura")
                        .WithMany("FacturaDetalle")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Servicio", "Servicio")
                        .WithMany("FacturaDetalles")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Terapia", "Terapia")
                        .WithMany()
                        .HasForeignKey("IdTerapia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Servicio");

                    b.Navigation("Terapia");
                });

            modelBuilder.Entity("Domain.Models.HistoriaAcademica", b =>
                {
                    b.HasOne("Domain.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("HistoriaAcademica")
                        .HasForeignKey("IdHistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HISTORIA_ACADEMICA_usario_actualizacion");

                    b.HasOne("Data.Models.User", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HISTORIA_ACADEMICA_usario_creacion");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Models.HistoriaClinica", b =>
                {
                    b.HasOne("API.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HISTORIA_CLINICA_paciente");

                    b.HasOne("Data.Models.User", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HISTORIA_CLINICA_usario_actualizacion");

                    b.HasOne("Data.Models.User", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_HISTORIA_CLINICA_usario_creacion");

                    b.Navigation("Paciente");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Models.Hobbies", b =>
                {
                    b.HasOne("API.Models.DatosPersonale", "IdDatosPersonalesNavigation")
                        .WithMany("Hobbies")
                        .HasForeignKey("IdDatosPersonales")
                        .IsRequired()
                        .HasConstraintName("FK_hobbies_datospersonales");

                    b.HasOne("Data.Models.User", "User")
                        .WithOne("Hobbies")
                        .HasForeignKey("Domain.Models.Hobbies", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDatosPersonalesNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.MentalPersonal", b =>
                {
                    b.HasOne("Domain.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("MentalPersonal")
                        .HasForeignKey("IdHistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MENTAL_PERSONAL_usario_actualizacion");

                    b.HasOne("Data.Models.User", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MENTAL_PERSONAL_usario_creacion");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Models.Pagos", b =>
                {
                    b.HasOne("Domain.Models.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("Domain.Models.RazonesSintomasConducta", b =>
                {
                    b.HasOne("Domain.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("RazonesSintomasConducta")
                        .HasForeignKey("IdHistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RAZONES_DE_SINTOMAS_CONDUCTA_usario_actualizacion");

                    b.HasOne("Data.Models.User", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RAZONES_DE_SINTOMAS_CONDUCTA_usario_creacion");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Models.Sala", b =>
                {
                    b.HasOne("Domain.Models.Cita", "cita")
                        .WithOne("sala")
                        .HasForeignKey("Domain.Models.Sala", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });

            modelBuilder.Entity("Domain.Models.SignosFisicos", b =>
                {
                    b.HasOne("Domain.Models.HistoriaClinica", "HistoriaClinica")
                        .WithMany("SignosFisicos")
                        .HasForeignKey("IdHistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SIGNOS_FISICOS_usario_actualizacion");

                    b.HasOne("Data.Models.User", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SIGNOS_FISICOS_usario_creacion");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Models.Terapia", b =>
                {
                    b.HasOne("API.Models.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("Idpsicologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("Idservicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Psicologo");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Domain.Models.carrito_de_compra", b =>
                {
                    b.HasOne("API.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Psicologo", "Psicologo")
                        .WithMany()
                        .HasForeignKey("IdPsicologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUsuarioActualizacion");

                    b.Navigation("Paciente");

                    b.Navigation("Psicologo");

                    b.Navigation("Servicio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.DatosPersonale", b =>
                {
                    b.Navigation("Hobbies");

                    b.Navigation("Paciente")
                        .IsRequired();

                    b.Navigation("Psicologos");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.Especialidad", b =>
                {
                    b.Navigation("PsicologoEspecialidads");
                });

            modelBuilder.Entity("API.Models.Idioma", b =>
                {
                    b.Navigation("PsicologoIdiomas");
                });

            modelBuilder.Entity("API.Models.Psicologo", b =>
                {
                    b.Navigation("Agenda")
                        .IsRequired();

                    b.Navigation("PsicologoEspecialidads");

                    b.Navigation("PsicologoIdiomas");

                    b.Navigation("PsicologoServicios");

                    b.Navigation("cita")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.Servicio", b =>
                {
                    b.Navigation("FacturaDetalles");

                    b.Navigation("PsicologoServicios");

                    b.Navigation("cita")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Perfil", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Navigation("Hobbies")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Cita", b =>
                {
                    b.Navigation("sala")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Factura", b =>
                {
                    b.Navigation("FacturaDetalle");
                });

            modelBuilder.Entity("Domain.Models.HistoriaClinica", b =>
                {
                    b.Navigation("ConceptoPsicologico");

                    b.Navigation("DesarrolloPsicosexual");

                    b.Navigation("ExamenEstadoMental");

                    b.Navigation("HistoriaAcademica");

                    b.Navigation("MentalPersonal");

                    b.Navigation("RazonesSintomasConducta");

                    b.Navigation("SignosFisicos");
                });
#pragma warning restore 612, 618
        }
    }
}
